### ISSUE TITLE
Getting things working on Windows

### ISSUE THREAD

**Issue by steveklabnik** [MichaelBurge/nes-emulator#1]
Hey there,

So, I can't 100% get this running (https://github.com/Rust-SDL2/rust-sdl2/issues/865), but I wanted to show you a diff that I *think* will get things working:

```diff
diff --git a/src/headless.rs b/src/headless.rs
index dbe25e0..73f831a 100644
--- a/src/headless.rs
+++ b/src/headless.rs
@@ -14,7 +14,6 @@ use std::io::Read;
 use std::io::Write;
 use std::fs::File;
 use std::fmt::Debug;
-use std::os::unix::io::FromRawFd;

 use crate::joystick::Joystick;
 use crate::mapper::AddressSpace;
@@ -27,8 +26,8 @@ use crate::common::Clocked;

 fn main() {
     // Standard stdout() object is line-buffered
-    let stdin = unsafe { File::from_raw_fd(0) };
-    let stdout = unsafe { File::from_raw_fd(1) };
+    let stdin = std::io::stdin();
+    let stdout = std::io::stdout();
     let mut headless = Headless::new(
         Box::new(stdin),
         Box::new(stdout),
```

In general, using the standard library here helps with portability. Of course, it's your project, and so feel free to ignore/close this issue!

**Comment by MichaelBurge** [comment]
I used a file descriptor because the `stdout` object is line-buffered, and my binary protocol does not use newlines after every command.

It looks like there isn't any way to shut this off:
```rust
#[stable(feature = "rust1", since = "1.0.0")]
pub struct Stdout {
    // FIXME: this should be LineWriter or BufWriter depending on the state of
    //        stdout (tty or not). Note that if this is not line buffered it
    //        should also flush-on-panic or some form of flush-on-abort.
    inner: Arc<ReentrantMutex<RefCell<LineWriter<Maybe<StdoutRaw>>>>>,
}
```
The `headless` binary isn't necessary to run the main emulator. I have Python code that uses it to train a Reinforcement Learning agent.

Is there a way to specify that `headless` is only built on Linux?

**Comment by steveklabnik** [comment]
Ah ha!

> Is there a way to specify that headless is only built on Linux?

A cheap way is to put `#![cfg(unix)]` at the top of `headless.rs`, so it just becomes an empty binary on non-unices. There's decent ways of specifying dependencies per platform, but not binaries.

Another strategy would be to do

```diff
diff --git a/src/headless.rs b/src/headless.rs
index dbe25e0..15b114b 100644
--- a/src/headless.rs
+++ b/src/headless.rs
@@ -14,7 +14,11 @@ use std::io::Read;
 use std::io::Write;
 use std::fs::File;
 use std::fmt::Debug;
+#[cfg(unix)]
 use std::os::unix::io::FromRawFd;
+#[cfg(windows)]
+use std::os::windows::io::FromRawHandle;
+

 use crate::joystick::Joystick;
 use crate::mapper::AddressSpace;
@@ -27,8 +31,24 @@ use crate::common::Clocked;

 fn main() {
     // Standard stdout() object is line-buffered
+    #[cfg(unix)]
     let stdin = unsafe { File::from_raw_fd(0) };
+
+    #[cfg(windows)]
+    let stdin = unsafe {
+        let h = winapi::um::processenv::GetStdHandle(winapi::um::winbase::STD_INPUT_HANDLE);
+        File::from_raw_handle(h)
+    };
+
+    #[cfg(unix)]
     let stdout = unsafe { File::from_raw_fd(1) };
+
+    #[cfg(windows)]
+    let stdout = unsafe {
+        let h = winapi::um::processenv::GetStdHandle(winapi::um::winbase::STD_OUTPUT_HANDLE);
+        File::from_raw_handle(h)
+    };
+
     let mut headless = Headless::new(
         Box::new(stdin),
         Box::new(stdout),
```

and add

```toml
[target.'cfg(windows)'.dependencies]
winapi = "0.3.6"
```

to `Cargo.toml`.

**Comment by MichaelBurge** [comment]
Thanks for the tips. I added a `#![cfg(unix)]` line at the top. I'll leave the Windows-specific code out since there's a good chance it could bitrot, but it's good to know there's an equivalent.

**Comment by MichaelBurge** [comment]
@steveklabnik FYI, someone managed to get this to compile and run on Windows by statically-linking SDL. Here's the command they used:

`cargo run --release --bin nes-emulator --features 'sdl2/bundled'`
