### ISSUE TITLE
Error on nightly Rust

### ISSUE THREAD

**Issue by steveklabnik** [MichaelBurge/nes-emulator#2]
Building with `nightly` instead of stable produces:

```text
error[E0597]: `texture_creator` does not live long enough
   --> src\main.rs:96:32
    |
96  |     let mut texture = Box::new(texture_creator.create_texture(
    |                                ^^^^^^^^^^^^^^^ borrowed value does not live long enough
...
142 |         texture: &mut *texture,
    |                  ------------- cast requires that `texture_creator` is borrowed for `'static`
...
179 | }
    | - `texture_creator` dropped here while still borrowed

```

I am not sure *why* this is an error in nightly but not in stable...

Anyway, what it's complaining about is this: as main ends, `texture_creator` will be freed, and then `GLOBAL_STATE` will be holding invalid memory; any destructors that run after `texture_creator` is freed could access that invalid memory.

Ideally, `GLOBAL_STATE` would use [`lazy_static`](https://crates.io/crates/lazy_static), I think. Not 100% sure how much contortion that would take.

**Comment by zackintosh** [comment]
This also currently happens on the latest `stable` (1.35.0)

**Comment by zackintosh** [comment]
This error also currently happens on the latest stable toolchain (1.35.0)

**Comment by MichaelBurge** [comment]
It should compile and run on both stable and nightly now.
