### ISSUE TITLE
Why not use buffered stdout instead of File::from_raw_fd(1)?

### ISSUE THREAD

**Issue by kpp** [MichaelBurge/nes-emulator#6]
https://github.com/MichaelBurge/nes-emulator/blob/0b9e321832360b93ed6fcd9d54bb3c3f11eca00a/src/headless.rs#L30

What's wrong with line-buffered stdout?

**Comment by MichaelBurge** [comment]
The `headless` executable uses a binary protocol to communicate with some Python code I'm using for Reinforcement Learning. The protocol doesn't end commands or responses with newlines, and both processes are expected to send their bytes immediately to avoid deadlocks.
